### ISSUE TITLE
Hi,do we  support Embedding layer?

### ISSUE THREAD

**Issue by mullerhai** [jworr/metatorch#1]

**Comment by jworr** [comment]
We could add another `Layer` [here](https://github.com/jworr/metatorch/blob/main/Layer.hs) and the corresponding code generation [here](https://github.com/jworr/metatorch/blob/main/Generate.hs)

**Comment by jworr** [comment]
I just added support for an embedding layer.

**Comment by mullerhai** [comment]
> I just added support for an embedding layer.

very thanks
